# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install any dependencies
RUN npm install

# Bundle the app's source code inside the Docker image
COPY . .

# Make port available to the world outside this container
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "start"]
