# Stage 1: Build the Vue.js application

# Use an official Node.js runtime as a parent image
FROM node:latest as build-stage

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the project files into the Docker image
COPY . .

# Build the app for production
RUN npm run build


# Stage 2: Serve the app with Nginx

# Use an official Nginx image
FROM nginx:stable as production-stage

# Copy built assets from build stage to Nginx's serve directory
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx and serve the application
CMD ["nginx", "-g", "daemon off;"]
