name: Update Manual Installer

on:
  # Runs every Sunday at midnight (UTC)
  schedule:
    - cron: '0 0 * * 0'
  # Allows you to manually trigger the workflow too
  workflow_dispatch:

jobs:
  update-manual-install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      
      - name: Run update script
        run: |
          python -m services.update_manual_install
      
      - name: Commit changes
        run: |
          git config --global user.name "Jaton Justice"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add .
          git commit -m "Weekly automated manual installer update" || echo "No changes to commit"
          git push
